name: Github-Client
options:
  bundleIdPrefix: jp.exam
packages:
  Apollo:
    url: https://github.com/apollographql/apollo-ios.git
    from: 0.20.0
targets:
  Github-Client:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Github-Client
    dependencies:
      - target: API
      - target: Domain
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"  
  Github-ClientTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Github-ClientTests
    dependencies:
      - target: Github-Client
  API:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - API
    dependencies:
      - package: Apollo
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "jp.exam.Github-Client.API"
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Domain
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "jp.exam.Github-Client.Domain"  
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DomainTests
    dependencies:
      - target: Domain
