name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Project builds
      run: ./setup.sh
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.4.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Generate Xcodegen
      run: xcodegen
    - name: Build
      run: xcodebuild
            -scheme Github-Client
            -sdk iphonesimulator
            -configuration Debug
            build
    - name: Run tests
      run: xcodebuild
            -scheme Github-Client
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
            clean test
