name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Project builds
      run: ./setup.sh
#     - name: Generate Xcodegen
#       run: xcodegen
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
